### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/venues#4]
The project needs a .gitignore file. Partially to keep out the riff raff but sooner than later we'll move configuration settings to a config file and we won't want those details going public. 

Here's the main .gitignore file for the CASH platform:
https://github.com/cashmusic/platform/blob/master/.gitignore

And here's more about the concept in general:
https://help.github.com/articles/ignoring-files/

**Comment by paperscissors** [comment]
Except obviously in this repo we need the *.sql.
